---
apiVersion: v1
kind: Pod # Pod is a collection of containers that can run on a host
metadata:
  name: cka-goglides-dev-pod # name of the pod
  labels:
    app: cka-goglides-dev # label for the pod
    tier: pod 
spec: 
  containers:
  - name: cka-goglides-dev-pod # name of the container
    image: nginx:1.13 # image to use
    imagePullPolicy: Always # Always pull the image from the registry, if not present locally. This is the default.
    ports:
    - containerPort: 8080 # port to expose
      protocol: TCP # protocol to use for the port mapping ( example TCP, UDP, or SCTP)
    volumeMounts:
    - name: cka-goglides-dev-volume # name of the volume
      mountPath: /usr/share/nginx/html # path to mount the volume to (example /usr/share/nginx/html)
      readOnly: true # read only access to the volume
  volumes:
  - name: cka-goglides-dev-volume # name of the volume
    emptyDir: {} # empty directory to mount to the pod (example /usr/share/nginx/html), data will lost if the pod is restarted
