---
apiVersion: v1
kind: Secret
metadata:
  name: cka-goglides-dev-secret
type: Opaque
stringData:
  username: "admin"
  password: "superSecret"
---
apiVersion: v1
kind: Pod # Pod is a collection of containers that can run on a host
metadata:
  name: cka-goglides-dev-pod # name of the pod
  labels:
    app: cka-goglides-dev # label for the pod
    tier: pod 
spec: 
  containers:
  - name: cka-goglides-dev-pod # name of the container
    image: nginx:1.13 # image to use
    imagePullPolicy: Always # Always pull the image from the registry, if not present locally. This is the default.
    ports:
    - containerPort: 8080 # port to expose
      protocol: TCP # protocol to use for the port mapping ( example TCP, UDP, or SCTP)
    volumeMounts:
    - name: secretpath
      mountPath: "/etc/app/secrets"
      readOnly: true
  volumes:
  - name: secretpath
    secret:
      secretName: cka-goglides-dev-secret
  # Since we added taint on previous steps, we need to make sure that the pod is tolerating that taint.
  # kubectl taint node minikube lowresource=true:NoSchedule
  # You can also remove taint from the node as follows
  # kubectl taint node minikube lowresource=true:NoSchedule-
  tolerations:
  - key: lowresource 
    operator: Exists
    effect: NoSchedule