---
apiVersion: v1
kind: Pod # Pod is a collection of containers that can run on a host
metadata:
  name: cka-goglides-dev-pod # name of the pod
  labels:
    app: cka-goglides-dev # label for the pod
    tier: pod 
spec: 
  containers:
  - name: cka-goglides-dev-pod # name of the container
    image: nginx:1.13 # image to use
    imagePullPolicy: Always # Always pull the image from the registry, if not present locally. This is the default.
    ports:
    - containerPort: 8080 # port to expose
      protocol: TCP # protocol to use for the port mapping ( example TCP, UDP, or SCTP)
  nodeName: minikube
