apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grailsapp
  template:
    metadata:
      labels:
        app: grailsapp
    spec:
      containers:
      - name: frontend
        imagePullPolicy: IfNotPresent
        image: bkpandey/kubernetes-certification-grails:v0.2
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 60
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 120
          periodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: goglides
    tier: service
spec:
  selector:
    app: grailsapp
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: ClusterIP
  sessionAffinity: None 

