apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: "standard" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: mysql-pv
---
