apiVersion: v1
kind: Service
metadata:
  name: myapp # name of the service
  labels:
    app: myapp # label for the service
    tier: service
spec:
  ports:
  - port: 80
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  # name here should match the name of the service
  name: myapp
  labels:
    app: myapp
    tier: service
subsets:
  # endpoints ip must not be loopback address
  # endpoints ip can not be the service ips of other services, because kube-proxy doesn't support virtual ips
  - addresses:
      - ip: 172.17.0.7
    ports:
      - port: 9090
        protocol: TCP