apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: goglides
  name: goglides
spec:
  containers:
  - image: goglides:v1.2.3
    name: goglides
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}