apiVersion: v1
kind: ServiceAccount
metadata:
  name: goglides-serviceaccount
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-goglides-pods
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-goglides-pods
  namespace: default
subjects:
- kind: ServiceAccount
  name: goglides-serviceaccount
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: read-goglides-pods
  apiGroup: rbac.authorization.k8s.io