---
apiVersion: apps/v1 # version of the Kubernetes API
kind: StatefulSet # StatefulSet is a collection of pods with a common management policy. StatefulSets are best used for pods that are long running or do not need to be restarted frequently.
metadata:
  name: mystatefulset # name of the statefulset
spec:
  selector:
    matchLabels:
      app: myapp # label for the statefulset
  serviceName: myapp # name of the service, its a headless service, used to control the network domain
  replicas: 10 # number of replicas
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: k8s.gcr.io/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  updateStrategy:
    type: OnDelete # OnDelete Pods are recreated from the StatefulSetSpec when they are manually deleted.
    # kubectl delete po mystatefulset-1
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
